# Generated by Django 4.2 on 2023-10-16 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Show', 'Show'), ('Festival', 'Festival')], max_length=14)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adress', models.CharField(max_length=255)),
                ('uf', models.CharField(blank=True, choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('DistritoFederal', 'Distritofederal'), ('EspíritoSanto', 'Espíritosanto'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('MatoGrosso', 'Matogrosso'), ('MatoGrossodoSul', 'Matogrossodosul'), ('MinasGerais', 'Minasgerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('RiodeJaneiro', 'Riodejaneiro'), ('RioGrandedoNorte', 'Riograndedonorte'), ('RioGrandedoSul', 'Riograndedosul'), ('Rondônia', 'Rondônia'), ('Roraima', 'Roraima'), ('SantaCatarina', 'Santacatarina'), ('SãoPaulo', 'Sãopaulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=16, null=True)),
                ('state', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=14)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
                'ordering': ['-created_at'],
            },
        ),
    ]
